'''1.	Write a python program to calculate area of 10 different circles.
   Given the pie = 22/7 and radius of the circles entered by user using Simple Function ,
   Parameterized Function , Return Type with function and return type with parameterized Functions.'''

def area1() :
  l = []
  for i in range(1, 11) :
    a = (i * i * 22) / 7
    l.append(a)
  return l

def area2(r):
  a = (r * r * 22) / 7
  return a

print("1. Area automatically generated")
print("2. Area generated by user's input")

ch = int(input("Enter your choice (1/2) : "))

if ch == 1 :
  print("Area of circles :")
  for x in area1() :
      print(x, "sq.unit")
elif ch == 2 :
  run = 10

  while (run > 0) :
    u = eval(input("Enter a number : "))
    print("Area of circle : ", area2(u), "sq. unit\n")
    
    run -= 1
