'''2.	Write a python program to print Multiplication tables from 2 to 20
      whether table values entered by user using Simple Function , 
      Parameterized Function , Return Type with function and return type
      with parameterized Functions.'''

def table1() :
  for i in range(2, 21) :
    for j in range(1, 11) :
      t = i * j
      print(i, " x ", j, " = ", t)
    print("\n")

def table2(a):
  for i in range(1, 11) :
    print(a, " x ", i, " = ", a * i, "\n")

print("1. Area automatically generated")
print("2. Area generated by user's input")

ch = int(input("Enter your choice (1/2) : "))

if ch == 1 :
  print("Automated tables :\n", table1())

elif ch == 2 :
  run = True
  
  while (run) :
    c = int(input("Enter a number : "))
    print("Table :\n", table2(c))
    
    c2 = input("Do you want to continue (y/n) : ")
    
    if (c2 == "y") or (c2 == "Y") :
      pass
    elif (c2 == "n") or (c2 == "N") :
      run = False
