'''1.	Write a python program to calculate area of 10 different circles.
   Given the pie = 22/7 and radius of the circles entered by user using Simple Function ,
   Parameterized Function , Return Type with function and return type with parameterized Functions.'''

def area1() :
  l = []
  for i in range(1, 11) :
    a = (i * i * 22) / 7
    l.append(a)
  for j in l :
    return j

def area2(r):
  a = (r * r * 22) / 7
  return a

print("1. Area automatically generated")
print("2. Area generated by user's input")

ch = int(input("Enter your choice (1/2) : "))

if ch == 1 :
  print("Area of circles : \n", area1())
elseif ch == 2 :
  run = 10

  while (run > 0) :
    u = eval(input("Enter a number : "))

    if (type(u) == int) or (type(u) == float) :
      print("Area of circle : ", area2(u), "sq. unit\n")
    else :
      print("Inserted input isn't suitable for function use.\n")
    
    run -= 1
